apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngx-deploy
  name: ngx-deploy
  namespace: techtalk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngx-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngx-deploy
    spec:
      containers:
      - image: nginx
        name: nginx-great
        resources: {}
status: {}
